version: 2.1

executors:
  php703:
    environment:
      COMPOSER_NO_INTERACTION: '1'
      BASH_ENV: '/root/.bashrc'
      phpName: '70308-nts'
    docker:
      -
        image: 'sweetchuck/php-env-dev:703-12.x.x'
        entrypoint: ['/bin/bash']

commands:
  composer_install:
    description: 'Install Composer dependencies with cache restore and save'
    steps:
      -
        restore_cache:
          name: 'Composer - cache restore'
          keys:
            - 'v1-dependencies-{{ checksum "composer.lock" }}'
            - 'v1-dependencies-'

      -
        run:
          name: 'Composer - install'
          command: >
            composer install --no-progress

      -
        save_cache:
          name: 'Composer - cache save'
          key: 'v1-dependencies-{{ checksum "composer.lock" }}'
          paths:
            - './bin/'
            - './docroot/core/'
            - './docroot/modules/contrib/'
            - './docroot/themes/contrib/'
            - './docroot/profiles/contrib/'
            - './docroot/libraries/contrib/'
            - './vendor/'

  lint:
    description: 'Run linters'
    steps:
      -
        run:
          name: 'Run linters'
          command: >
            bin/drush --config=drush @app.local marvin:lint:phpcs

  test_unit:
    description: 'Run unit tests'
    steps:
      -
        run:
          name: 'Run unit tests'
          command: >
            bin/drush --config=drush @app.local marvin:test:unit
      -
        store_test_results:
          name: 'Store unit test results'
          path: 'reports/machine/junit'
      -
        run:
          name: 'Publish the code coverage report on Codecov.io'
          when: 'always'
          command: >
            [ ! -s reports/machine/coverage/*/coverage.xml ]
            || bash <(curl -s https://codecov.io/bash)
            || true

jobs:
  php703__lint_and_test:
    executor: 'php703'
    working_directory: '~/repo'
    steps:
      - 'checkout'
      - 'composer_install'
      - 'lint'

workflows:
  php703__lint_and_test:
    jobs:
      - 'php703__lint_and_test'
